training_config:
  game: "connect_four"
  size: [4, 4]
  dataset_path: "/Users/zaheen/projects/node_arena/python/connect_four_4_4.h5"
  policy_type: "dense"
  num_iterations: 0
  num_epochs: 10
  batch_size: 64
  eval_interval: 100
  ckpt_path: "/Users/zaheen/Documents/node_arena/connect_four/checkpoints"
optimizer_config:
  name: "sgd"
  kwargs:
    learning_rate: 0.001
    momentum: 0.99
model_config:
  name: "CNN"
  seed: 0
