"""
game_protocols.py

Author: Zaheen Ahmad

Defines types for games:
    ActionType
    State
    Game
"""

from typing import Any, Protocol, TypeVar

ActionType = TypeVar("ActionType")


class State(Protocol):
    def __init__(self) -> None: ...
    def print_board(self, *args: Any, **kwargs: Any) -> None: ...
    def state_to_string(self, *args: Any, **kwargs: Any) -> Any: ...
    def string_to_state(self, *args: Any, **kwargs: Any) -> None: ...
    def get_player(self) -> Any: ...
    def set_player(self, *args: Any, **kwargs: Any) -> None: ...


class Game(Protocol[ActionType]):
    def __init__(self) -> None: ...
    def reset(self, *args: Any, **kwargs: Any) -> None: ...
    def get_actions(self, *args: Any, **kwargs: Any) -> list[ActionType]: ...
    def apply_action(self, *args: Any, **kwargs: Any) -> int: ...
    def get_next_state(self, *args: Any, **kwargs: Any) -> State: ...
    def is_winner(self, *args: Any, **kwargs: Any) -> bool: ...
    def is_draw(self, *args: Any, **kwargs: Any) -> bool: ...
