"""
game_protocols.py

Author: Zaheen Ahmad

Defines types for games:
    ActionType
    State
    Game
"""

from enum import Enum
from typing import Any, Protocol, TypeVar

ActionType = TypeVar("ActionType")


class Outcomes(Enum):
    NonTerminal = 0
    P1Win = 1
    P2Win = 2
    Draw = 3


class Player(Enum):
    One = 0
    Two = 1


class StateProtocol(Protocol):
    Player: Any

    def __init__(self) -> None: ...
    def print_board(self, *args: Any, **kwargs: Any) -> None: ...
    def to_array(self) -> list[list[int]]: ...
    def to_string(self, *args: Any, **kwargs: Any) -> str: ...
    def from_string(self, *args: Any, **kwargs: Any) -> None: ...
    def get_player(self) -> Any: ...
    def get_opponent(self) -> Any: ...
    def set_player(self, *args: Any, **kwargs: Any) -> None: ...


class GameProtocol(Protocol[ActionType]):
    Outcomes: Any

    def __init__(self) -> None: ...
    def get_id(self) -> str: ...
    def reset(self, *args: Any, **kwargs: Any) -> None: ...
    def get_actions(self, *args: Any, **kwargs: Any) -> list[ActionType]: ...
    def apply_action(self, *args: Any, **kwargs: Any) -> int: ...
    def get_next_state(self, *args: Any, **kwargs: Any) -> StateProtocol: ...
    def is_winner(self, *args: Any, **kwargs: Any) -> bool: ...
    def is_draw(self, *args: Any, **kwargs: Any) -> bool: ...
    def is_terminal(self, *args: Any, **kwargs: Any) -> bool: ...
    def get_outcome(self, *args: Any, **kwargs: Any) -> Any: ...
    def legal_moves_mask(self, *args: Any, **kwargs: Any) -> list[int]: ...
